update

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,9 +1,10 @@
 branch="$(git rev-parse --abbrev-ref HEAD)"
 
-if [ "$branch" = "main" ]; then
-  echo "You can't commit directly to main - please check out a branch."
-  exit 1
-fi
+# kilocode_change - Allow direct commits to main branch
+# if [ "$branch" = "main" ]; then
+#   echo "You can't commit directly to main - please check out a branch."
+#   exit 1
+# fi
 
 # Detect if running on Windows and use pnpm.cmd, otherwise use pnpm.
 if [ "$OS" = "Windows_NT" ]; then
